openapi: 3.0.1
info:
  title: Replicate models
  description: A plugin that allows the user to run Replicate models from ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /collections:
    post:
      operationId: getCollections
      summary: get a list of available collections, descriptions and their slugs
      responses:
        "200":
          description: OK
  /collection:
    post:
      operationId: getCollection
      summary: get a list of models in a collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getCollectionRequest'
      responses:
        "200":
          description: OK
  /model:
    post:
      operationId: getModel
      summary: get information about a model and how to run it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getModelRequest'
      responses:
        "200":
          description: OK
  /run:
    post:
      operationId: runModel
      summary: run a model on Replicate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runModelRequest'
      responses:
        "200":
          description: OK

components:
  schemas:
    Model:
      type: object
      properties:
        username:
          type: string
          description: The owner of the model
        model:
          type: string
          description: The name of the model
        input:
          type: object
          description: The input data to be passed to the model
      required:
        - username
        - model
        - input
    runModelRequest:
      type: object
      properties:
        models:
          type: array
          description: An array of models and their inputs
          items:
            $ref: '#/components/schemas/Model'
      required:
        - models
    runModelResponse:
      type: string
      description: JSON representation of an array of the outputs from the models
    getCollectionRequest:
      type: object
      properties:
        collection_slug:
          type: string
          description: slug of the collection
          required: true
    getModelResponse:
      type: array,
      description: An array containing each of the model outputs,
      items:
        type: object,
        properties:
          output:
            type: string,
            description: The output from the model
    getModelRequest:
      type: object
      properties:
        username:
          type: string
          description: owner of the model
          required: true
        model:
          type: string
          description: name of the model
          required: true
      required:
        - username
        - model
