openapi: 3.0.1
info:
  title: Replicate models
  description: A plugin that allows the user to run Replicate models from ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /getModelSchemas:
    post:
      operationId: getInfo
      summary: get information about models and how to run them
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getInfoRequest'
      responses:
        "200":
          description: OK
  /run:
    post:
      operationId: runModels
      summary: run models on Replicate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runModelsRequest'
      responses:
        "200":
          description: OK

components:
  schemas:
    SchemaModel:
      type: object
      properties:
        username:
          type: string
          description: The owner of the model
        model:
          type: string
          description: The name of the model
      required:
        - username
        - model
    RunModel:
      type: object
      properties:
        username:
          type: string
          description: The owner of the model
        model:
          type: string
          description: The name of the model
        input:
          type: object
          description: The input data to be passed to the model
      required:
        - username
        - model
        - input
    runModelsRequest:
      type: object
      properties:
        models:
          type: array
          description: An array of models and their inputs
          items:
            $ref: '#/components/schemas/RunModel'
      required:
        - models
    runModelsResponse:
      type: string
      description: JSON representation of an array of the outputs from the models
    getInfoResponse:
      type: array,
      description: An array containing each of the model outputs,
      items:
        type: object,
        properties:
          output:
            type: string,
            description: The output from the model
    getInfoRequest:
      type: object
      properties:
        schemas:
          type: array
          description: An array of usernames and model names
          items:
            $ref: '#/components/schemas/SchemaModel'
      required:
        - schemas
